### ISSUE TITLE
Make selected background image more clear

### ISSUE THREAD

**Issue by AlveBrekXtreme** [FarouqJalabi/TaskWave#1]
I would suggest a minor improvment to the design. The border that indicates which background is selected is not that visible. Maybe change the color or gray out/change the opacity of images that are not selected
![image](https://github.com/FarouqJalabi/TaskWave/assets/114334244/ebddf78e-d3bd-42ee-97a0-e340b897bb9d)

**Comment by FarouqJalabi** [comment]
Agree will happened big boss🫡

**Comment by FarouqJalabi** [comment]
![image](https://github.com/FarouqJalabi/TaskWave/assets/139611840/66b18664-34be-467e-9379-18177d56b0fd)
The images become smaller and scaled out to indicate that they are not selected.
